//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceGen.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GstStateCode
    {
        public long ID { get; set; }
        public string GSTStateCode1 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> StateID { get; set; }
    
        public virtual State State { get; set; }
    }
}
