CREATE TABLE [dbo].[Customers] (
    [ID]            BIGINT         IDENTITY (1, 1) NOT NULL,
    [FirstName]     NVARCHAR (100) NULL,
    [MiddleName]    NVARCHAR (100) NULL,
    [LastName]      NVARCHAR (100) NOT NULL,
    [EmailID]       NVARCHAR (200) NULL,
    [CustomerType]  NVARCHAR (100) NOT NULL,
    [ContactName]   NVARCHAR (400) NOT NULL,
    [ContactNumber] NVARCHAR (30)  NULL,
    [Gstin]         NVARCHAR (40)  NULL,
    [PAN]           NVARCHAR (40)  NULL,
    [BAddL1]        NVARCHAR (100) NULL,
    [BAddL2]        NVARCHAR (100) NULL,
    [BAddCity]      NVARCHAR (100) NULL,
    [BAddState]     NVARCHAR (100) NULL,
    [BAddZip]       NVARCHAR (100) NULL,
    [SAddL1]        NVARCHAR (100) NULL,
    [SAddL2]        NVARCHAR (100) NULL,
    [SAddCity]      NVARCHAR (100) NULL,
    [SAddState]     NVARCHAR (100) NULL,
    [SAddZip]       NVARCHAR (100) NULL,
    [IsActive]      BIT            DEFAULT ((1)) NULL,
    [CreatedOn]     DATETIME       DEFAULT (getdate()) NULL,
    [UpdatedOn]     DATETIME       NULL,
    [CreatedBy]     BIGINT         NULL,
    [UpdatedBy]     BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

