//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceGen.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillMaster()
        {
            this.BillProductMappings = new HashSet<BillProductMapping>();
        }
    
        public long ID { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public Nullable<long> BillFromCustID { get; set; }
        public Nullable<long> BillToCustID { get; set; }
        public string ShippAddress { get; set; }
        public string BillAddress { get; set; }
        public string TermsConditions { get; set; }
        public string NotesForCustomer { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillProductMapping> BillProductMappings { get; set; }
    }
}
