//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceGen.DAL
{
    using InvoiceGen.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InvoiceGenEntities : DbContext
    {
        public InvoiceGenEntities()
            : base("name=InvoiceGenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BillMaster> BillMasters { get; set; }
        public virtual DbSet<BillProductMapping> BillProductMappings { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CustomerProductMapping> CustomerProductMappings { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<GstStateCode> GstStateCodes { get; set; }
        public virtual DbSet<OperationMaster> OperationMasters { get; set; }
        public virtual DbSet<ProductsMaster> ProductsMasters { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<RoleOperationMapping> RoleOperationMappings { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<UserRoleMapping> UserRoleMappings { get; set; }
    }
}
