//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceGen.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleOperationMapping
    {
        public long ID { get; set; }
        public Nullable<long> RoleId { get; set; }
        public Nullable<long> OperationId { get; set; }
    
        public virtual OperationMaster OperationMaster { get; set; }
        public virtual RoleMaster RoleMaster { get; set; }
    }
}
